In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity 
import requests
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [12]:
pokemon = pd.read_csv('Pokemon.csv')
pokemon.head(2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False

In [13]:
pokemon.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
a = CountVectorizer()

In [14]:
def Combination(i):
    return str(i['Type 1'])+ '$' +str(i['Generation'])+'$'+str(i['Legendary'])
pokemon['Atribute']= poke.apply(Combination,axis=1)
pokemon['Name']= poke['Name'].apply(lambda i: i.lower())

pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Atribute
0,1,bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Grass$1$False
1,2,ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Grass$1$False
2,3,venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Grass$1$False
3,3,venusaurmega venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Grass$1$False
4,4,charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Fire$1$False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Rock$6$True
796,719,dianciemega diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Rock$6$True
797,720,hoopahoopa confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Psychic$6$True
798,720,hoopahoopa unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Psychic$6$True
799,721,volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Fire$6$True

In [15]:
co = CountVectorizer(tokenizer=lambda poke: poke.split('$'))
pokeU = co.fit_transform(pokemon['Atribute'])
skorPoke = cosine_similarity(pokeU)
skorPoke

array([[1.        , 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.66666667],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.66666667],
       [0.        , 0.        , 0.        , ..., 0.66666667, 0.66666667,
        1.        ]])

In [16]:
pokeSuka = "pikachu"
indexSuka = pokemon[pokemon["Name"] == pokeSuka].index[0]
indexSuka

pokeRekom = list(enumerate(skorPoke[indexSuka]))
pokeSamaSortir = sorted(pokeRekom, key= lambda x:x[1], reverse= True)
pokeSamaSortir[:10]

[(30, 1.0000000000000002),
 (31, 1.0000000000000002),
 (88, 1.0000000000000002),
 (89, 1.0000000000000002),
 (108, 1.0000000000000002),
 (109, 1.0000000000000002),
 (134, 1.0000000000000002),
 (146, 1.0000000000000002),
 (0, 0.6666666666666669),
 (1, 0.6666666666666669)]

In [17]:
Rekomen = []
for i in pokeSamaSortir[:7]:
    if i[0] != indexSuka:
        Rekomen.append(pokemon.iloc[i[0]])
    
dfRekomen = pd.DataFrame(Rekomen)
dfRekomen

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Atribute
31,26,raichu,Electric,NaN,485,60,90,55,90,80,110,1,False,Electric$1$False
88,81,magnemite,Electric,Steel,325,25,35,70,95,55,45,1,False,Electric$1$False
89,82,magneton,Electric,Steel,465,50,60,95,120,70,70,1,False,Electric$1$False
108,100,voltorb,Electric,NaN,330,40,30,50,55,55,100,1,False,Electric$1$False
109,101,electrode,Electric,NaN,480,60,50,70,80,80,140,1,False,Electric$1$False
134,125,electabuzz,Electric,NaN,490,65,83,57,95,85,105,1,False,Electric$1$False

In [9]:
url = 'https://pokeapi.co/api/v2/pokemon/'+ str(4)
url = requests.get(url)
pic = url.json()["sprites"]["front_default"]
pic

'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png'

In [18]:
gambar = []

for i in pokemon["#"]:
    url = 'https://pokeapi.co/api/v2/pokemon/'+ str(i)
    url = requests.get(url)
    pic = url.json()["sprites"]["front_default"]
    gambar.append(pic)
pokemon["Pic"] = pd.DataFrame(gambar)
pokemon[:10]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Atribute,Pic
0,1,bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Grass$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
1,2,ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Grass$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
2,3,venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Grass$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
3,3,venusaurmega venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Grass$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
4,4,charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Fire$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
5,5,charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,Fire$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
6,6,charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,Fire$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
7,6,charizardmega charizard x,Fire,Dragon,634,78,130,111,130,85,100,1,False,Fire$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
8,6,charizardmega charizard y,Fire,Flying,634,78,104,78,159,115,100,1,False,Fire$1$False,https://raw.githubusercontent.com/PokeAPI/spri...
9,7,squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,Water$1$False,https://raw.githubusercontent.com/PokeAPI/spri...